data <- read.csv("household_power_consumption.txt", header = TRUE, sep = ";")
head(data)
str(data)
data$complete_time <- paste(data$Date, data$Time)
head(data)
data$time_converted <- strptime(data$complete_time, format = "%d/%m/%Y %H:%M:%S")
head(data)
needed_data <- subset(data, time_converted > as.POSIXlt ("2007-02-01 00:00:00")  & time_converted < as.POSIXlt("2007-02-03 00:00:00"))
head(needed_data)
needed_data$Global_active_power <- as.numeric(as.character(needed_data$Global_active_power))
str(needed_data)
needed_data$Sub_metering_1 <- as.numeric(as.character(needed_data$Sub_metering_1))
needed_data$Sub_metering_2 <- as.numeric(as.character(needed_data$Sub_metering_2))
str(needed_data)
needed_data$Voltage <- as.numeric(as.character(needed_data$Voltage))
str(needed_data)
needed_data$Global_reactive_power <- as.numeric(as.character(needed_data$Global_reactive_power))
str(needed_data)
